Add migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -216,7 +216,7 @@ jobs:
     docker:
       - image: williamyeh/ansible:ubuntu18.04
     environment:
-       TYPEORM_USERNAME: $TYPEORM_USERNAME 
+       TYPEORM_USERNAME2: $TYPEORM_USERNAME 
       
     steps:
       
@@ -227,7 +227,10 @@ jobs:
           at: ~/
       - run : 
          name: "check env varibales"  
-         command:  echo $TYPEORM_USERNAME 
+         command: |
+           echo $TYPEORM_USERNAME 
+           echo $TYPEORM_USERNAME2
+
       - run:
           name: Configure server
           environment:
@@ -239,25 +242,23 @@ jobs:
             ansible-playbook -i inventory.txt  configure-server.yml -vvv
       # Here's where you will add some code to rollback on failure    
 
-  deploy-backend:
+  run-migrations:
     docker:
-      - image: williamyeh/ansible:ubuntu18.04
+      - image: node
     steps:
       - checkout
-      - add_ssh_keys:
-          fingerprints: ["a5:c1:42:5d:4b:2c:12:c8:75:66:63:b5:75:77:2b:20"]
-      - attach_workspace:
-          at: ~/
       - run:
-          name: Install dependencies
+          name: Run migrations
           command: |
-            # your code here
+            cd backend/
+            npm run migrations
       - run:
-          name: Deploy backend
+          name: Send migration results to memstash
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
-  
+            echo TODO
+            # # Your code here
+            # exit 1
+     # Here's where you will add some code to rollback on failure  
 
 workflows:
   default:
@@ -279,8 +280,8 @@ workflows:
               only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
       # - deploy-backend:
